<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BienkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('bienk')->insert([ 'codigo' => 'ES00001', 'codigo_anterior' => 'ES00001','nombre' => 'ESTANTE DE MADERA','modelo' => '6 DIVISIONES','numero' =>1,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 1,'id_estado' =>2, 'observaciones' => 'COLOR AMARILLO  310 X 230 X 180CM']);
        DB::table('bienk')->insert([ 'codigo' => 'ES00002', 'codigo_anterior' => 'ES00002','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'EXTRA ANGOSTO','numero' =>2,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 1,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ME0001', 'codigo_anterior' => 'ME0001','nombre' => 'MESA DE MADERA','modelo' => 'SM','numero' =>3,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 1,'id_estado' =>3, 'observaciones' => 'PATA ROTA ']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0001', 'codigo_anterior' => 'SI0001','nombre' => 'SILLA DE METAL Y MADERA','modelo' => 'SM','numero' =>4,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 1,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0002', 'codigo_anterior' => 'SI0002','nombre' => 'SILLA DE METAL Y MADERA','modelo' => 'SM','numero' =>5,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 1,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0006', 'codigo_anterior' => 'ES0006','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>6,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 2,'id_estado' =>4, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0007', 'codigo_anterior' => 'CO0007','nombre' => 'COMPUTADORA PORTATIL HUAWEI','modelo' => 'E5470','numero' =>7,'serie' => 'KP2132','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 2,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MU0008', 'codigo_anterior' => 'MU0008','nombre' => 'MULTIFUNCIONAL HP','modelo' => 'LZ231','numero' =>8,'serie' => 'ML7855','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 2,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0009', 'codigo_anterior' => 'ES0009','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>9,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 3,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0010', 'codigo_anterior' => 'CO0010','nombre' => 'COMPUTADORA PORTATIL SAMSUNG','modelo' => 'SA6754','numero' =>10,'serie' => 'S102','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 3,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0011', 'codigo_anterior' => 'ET0011','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>11,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 3,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'PA0012', 'codigo_anterior' => 'PA0012','nombre' => 'PAPELERA DE METAL','modelo' => 'SM','numero' =>12,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 3,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0013', 'codigo_anterior' => 'SI0013','nombre' => 'SILLA DE METAL','modelo' => 'SM','numero' =>13,'serie' => 'SN','id_persona' =>1,'idpersona_otro' =>0,'id_area' => 3,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0014', 'codigo_anterior' => 'ET0014','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>14,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 4,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0015', 'codigo_anterior' => 'ET0015','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>15,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 4,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MS0016', 'codigo_anterior' => 'MS0016','nombre' => 'MESA DE MADERA','modelo' => 'SM','numero' =>16,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 4,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0017', 'codigo_anterior' => 'SI0017','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>17,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 4,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0018', 'codigo_anterior' => 'SI0018','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>18,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 4,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0019', 'codigo_anterior' => 'ES0019','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>19,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 5,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0020', 'codigo_anterior' => 'CO0020','nombre' => 'COMPUTADORA PORTATIL HP','modelo' => 'HP402','numero' =>20,'serie' => 'SPY27','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 5,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0021', 'codigo_anterior' => 'CO0021','nombre' => 'MULTIFUNCIONAL EPSON','modelo' => 'CD4321','numero' =>21,'serie' => 'EP2122','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 5,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0022', 'codigo_anterior' => 'ES0022','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>22,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 6,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0023', 'codigo_anterior' => 'CO0023','nombre' => 'COMPUTADORA TODO EN UNO HP','modelo' => 'HPLIGHT','numero' =>23,'serie' => 'H21332','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 6,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0024', 'codigo_anterior' => 'ET0024','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>24,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 6,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'PA0025', 'codigo_anterior' => 'PA0025','nombre' => 'PALERA DE MADERA','modelo' => 'SM','numero' =>25,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 6,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0026', 'codigo_anterior' => 'SI0026','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>26,'serie' => 'SN','id_persona' =>2,'idpersona_otro' =>0,'id_area' => 6,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0027', 'codigo_anterior' => 'ES0027','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>27,'serie' => 'SN','id_persona' =>3,'idpersona_otro' =>0,'id_area' => 7,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0028', 'codigo_anterior' => 'ET0028','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>28,'serie' => 'SN','id_persona' =>3,'idpersona_otro' =>0,'id_area' => 7,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0029', 'codigo_anterior' => 'CO0029','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN0321','numero' =>29,'serie' => 'L0321','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0030', 'codigo_anterior' => 'CO0030','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN0322','numero' =>30,'serie' => 'L0322','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0031', 'codigo_anterior' => 'CO0031','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN0323','numero' =>31,'serie' => 'L0323','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0032', 'codigo_anterior' => 'CO0032','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN0324','numero' =>32,'serie' => 'L0324','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MU0033', 'codigo_anterior' => 'MU0033','nombre' => 'MUEBLE DE MADERA PARA  COMPUTADORA','modelo' => 'SM','numero' =>33,'serie' => 'SN','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MU0034', 'codigo_anterior' => 'MU0034','nombre' => 'MUEBLE DE MADERA PARA  COMPUTADORA','modelo' => 'SM','numero' =>34,'serie' => 'SN','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0035', 'codigo_anterior' => 'SI0035','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>35,'serie' => 'SN','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0036', 'codigo_anterior' => 'SI0036','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>36,'serie' => 'SN','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0037', 'codigo_anterior' => 'SI0037','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>37,'serie' => 'SN','id_persona' =>4,'idpersona_otro' =>0,'id_area' => 8,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'LA0038', 'codigo_anterior' => 'LA0038','nombre' => 'LAPTOP TOSHIBA','modelo' => 'TO9001','numero' =>38,'serie' => 'T2103','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0039', 'codigo_anterior' => 'ET0039','nombre' => 'ESTANTE PARA SERVIDOR','modelo' => 'SM','numero' =>39,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'RO0040', 'codigo_anterior' => 'RO0040','nombre' => 'ROUTER CISCO 64 PUERTOS','modelo' => 'SM','numero' =>40,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0041', 'codigo_anterior' => 'CO0041','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN2121','numero' =>41,'serie' => 'L0001','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0042', 'codigo_anterior' => 'CO0042','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN2121','numero' =>42,'serie' => 'L0002','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0043', 'codigo_anterior' => 'CO0043','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN2121','numero' =>43,'serie' => 'L0003','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0044', 'codigo_anterior' => 'CO0044','nombre' => 'COMPUTADORA  LENOVO','modelo' => 'LN2121','numero' =>44,'serie' => 'L0004','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MU0045', 'codigo_anterior' => 'MU0045','nombre' => 'MUEBLE DE MADERA PARA  COMPUTADORA','modelo' => 'SM','numero' =>45,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MU0046', 'codigo_anterior' => 'MU0046','nombre' => 'MUEBLE DE MADERA PARA  COMPUTADORA','modelo' => 'SM','numero' =>46,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MU0047', 'codigo_anterior' => 'MU0047','nombre' => 'MUEBLE DE MADERA PARA  COMPUTADORA','modelo' => 'SM','numero' =>47,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0048', 'codigo_anterior' => 'SI0048','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>48,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0049', 'codigo_anterior' => 'SI0049','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>49,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0049', 'codigo_anterior' => 'SI0049','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>50,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 9,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ME0051', 'codigo_anterior' => 'ME0051','nombre' => 'MESA DE MADERA','modelo' => 'SM','numero' =>51,'serie' => 'SN','id_persona' =>3,'idpersona_otro' =>0,'id_area' => 10,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0052', 'codigo_anterior' => 'SI0052','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>52,'serie' => 'SN','id_persona' =>3,'idpersona_otro' =>0,'id_area' => 10,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0053', 'codigo_anterior' => 'CO0053','nombre' => 'COMPUTADORA LENOVO','modelo' => 'LN2121','numero' =>53,'serie' => 'L0005','id_persona' =>3,'idpersona_otro' =>0,'id_area' => 10,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'EC0054', 'codigo_anterior' => 'EC0054','nombre' => 'ESCALERA E METAL','modelo' => 'SM','numero' =>54,'serie' => 'SN','id_persona' =>3,'idpersona_otro' =>0,'id_area' => 10,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0055', 'codigo_anterior' => 'ES0055','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>55,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 11,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'RD0056', 'codigo_anterior' => 'RD0056','nombre' => 'REDAR DE ALIMENTACION','modelo' => 'SM','numero' =>56,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 11,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'BA0057', 'codigo_anterior' => 'BA0057','nombre' => 'BALANZA','modelo' => 'SM','numero' =>57,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 11,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'TA0058', 'codigo_anterior' => 'TA0058','nombre' => 'TALLIMETRO','modelo' => 'SM','numero' =>58,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 11,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'TV0059', 'codigo_anterior' => 'TV0059','nombre' => 'TELEVISOR LG 56 PULGADAS','modelo' => 'SM','numero' =>59,'serie' => 'SN','id_persona' =>5,'idpersona_otro' =>0,'id_area' => 11,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'RD0060', 'codigo_anterior' => 'RD0060','nombre' => 'REDAR DE DESNUTRICION','modelo' => 'SM','numero' =>60,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 12,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'TA0061', 'codigo_anterior' => 'TA0061','nombre' => 'TALLIMETRO PEDIATRICO','modelo' => 'SM','numero' =>61,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 12,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'BA0062', 'codigo_anterior' => 'BA0062','nombre' => 'BALANZA PEDIATRICA','modelo' => 'SM','numero' =>62,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 12,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'KT0063', 'codigo_anterior' => 'KT0063','nombre' => 'KIT DEL DESARROLLO','modelo' => 'SM','numero' =>63,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 12,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'BA0064', 'codigo_anterior' => 'BA0064','nombre' => 'BALANZA','modelo' => 'SM','numero' =>64,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 13,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'TA0065', 'codigo_anterior' => 'TA0065','nombre' => 'TALLIMETRO','modelo' => 'SM','numero' =>65,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 13,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'EO0066', 'codigo_anterior' => 'EO0066','nombre' => 'ESTETOSCOPIO','modelo' => 'SM','numero' =>66,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 13,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'TO0067', 'codigo_anterior' => 'TO0067','nombre' => 'TENSIOMETRO','modelo' => 'SM','numero' =>67,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 13,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'TM0068', 'codigo_anterior' => 'TM0068','nombre' => 'TERMOMETRO','modelo' => 'SM','numero' =>68,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 13,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'PO0069', 'codigo_anterior' => 'PO0069','nombre' => 'PULSO OXIMETRO','modelo' => 'SM','numero' =>69,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 13,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'BA0070', 'codigo_anterior' => 'BA0070','nombre' => 'BALANZA','modelo' => 'SM','numero' =>70,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 14,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0071', 'codigo_anterior' => 'ES0071','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>71,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 14,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'TV0072', 'codigo_anterior' => 'TV0072','nombre' => 'TERMA PARA VACUNAS','modelo' => 'SM','numero' =>72,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 15,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CR0072', 'codigo_anterior' => 'CR0072','nombre' => 'CONGELADOR LG','modelo' => 'SM','numero' =>73,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 15,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'EC0074', 'codigo_anterior' => 'EC0074','nombre' => 'EQUIPO DE CURACION','modelo' => 'SM','numero' =>74,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 16,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MP0075', 'codigo_anterior' => 'MP0075','nombre' => 'MESA DE MADERA PLEGABLE','modelo' => 'SM','numero' =>75,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 16,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CA0076', 'codigo_anterior' => 'CA0076','nombre' => 'CAMILLA','modelo' => 'SM','numero' =>76,'serie' => 'SN','id_persona' =>6,'idpersona_otro' =>0,'id_area' => 16,'id_estado' =>3, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0077', 'codigo_anterior' => 'ET0077','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>77,'serie' => 'SN','id_persona' =>7,'idpersona_otro' =>0,'id_area' => 17,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0078', 'codigo_anterior' => 'ET0078','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>78,'serie' => 'SN','id_persona' =>7,'idpersona_otro' =>0,'id_area' => 17,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ME0079', 'codigo_anterior' => 'ME0079','nombre' => 'MESA DE MADERA','modelo' => 'SM','numero' =>79,'serie' => 'SN','id_persona' =>7,'idpersona_otro' =>0,'id_area' => 17,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0080', 'codigo_anterior' => 'SI0080','nombre' => 'SILLA DE METAL','modelo' => 'SM','numero' =>80,'serie' => 'SN','id_persona' =>7,'idpersona_otro' =>0,'id_area' => 17,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0081', 'codigo_anterior' => 'SI0081','nombre' => 'SILLA DE METAL','modelo' => 'SM','numero' =>81,'serie' => 'SN','id_persona' =>7,'idpersona_otro' =>0,'id_area' => 17,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0082', 'codigo_anterior' => 'ES0082','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>82,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 18,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0083', 'codigo_anterior' => 'CO0083','nombre' => 'COMPUTADORA LENOVO','modelo' => 'SM','numero' =>83,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 18,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'MU0084', 'codigo_anterior' => 'MU0084','nombre' => 'MULTIFUNCIONAL','modelo' => 'SM','numero' =>84,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 18,'id_estado' =>2, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ES0085', 'codigo_anterior' => 'ES0085','nombre' => 'ESCRITORIO DE MADERA','modelo' => 'SM','numero' =>85,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 19,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'CO0086', 'codigo_anterior' => 'CO0086','nombre' => 'COMPUTADORA LENOVO','modelo' => 'SM','numero' =>86,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 19,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'ET0087', 'codigo_anterior' => 'ET0087','nombre' => 'ESTANTE DE MADERA','modelo' => 'SM','numero' =>87,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 19,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'PA0088', 'codigo_anterior' => 'PA0088','nombre' => 'PAPELERA DE METAL','modelo' => 'SM','numero' =>88,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 19,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);
        DB::table('bienk')->insert([ 'codigo' => 'SI0089', 'codigo_anterior' => 'SI0089','nombre' => 'SILLA DE MADERA','modelo' => 'SM','numero' =>89,'serie' => 'SN','id_persona' =>8,'idpersona_otro' =>0,'id_area' => 19,'id_estado' =>1, 'observaciones' => 'SIN OBSERVACIONES']);








    }
}
